title: Project

columns:
  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          description:
            type: textarea
          category:
            type: text
          year:
            type: text
          link:
            type: url

  - width: 1/2
    sections:
      gallery:
        type: files
        layout: cards
        image:
          ratio: 1/1
