title: Project

fields:
  blocks:
    width: 1/1
    type: blocks
    pretty: true
  gallery:
    width: 1/2
    type: files
    layout: cards
    query: page.images
  date:
    width: 1/4
    type: date
    time: false
    default: now
  tags:
    width: 1/4
    label: tags
    type: tags
