#!/usr/bin/env bash
#
# 정본 호스트(www → apex) 서버 설정 위저드 — 사람이 한 단계씩 실행한다.
#
# 2026-08-17에 한 번 실행되어 적용을 마쳤다. 서버를 다시 세우거나 인증서를
# 갈아끼운 뒤 www 리다이렉트가 되돌아갔을 때 다시 돌리기 위해 남겨둔다.
# 각 단계는 grep 가드와 확인 게이트가 있어 여러 번 돌려도 안전하다.
#
# 배경과 결정: docs/adr/0003-canonical-host.md
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# 이 위저드는 값을 수집하기보다 서버 상태를 바꾼다. 저장소를 더럽히지 않도록
# .env는 홈 아래 전용 파일에 둔다(재실행 시 SSH 주소를 기억하는 용도).
ENV_FILE="${ENV_FILE:-$HOME/.massivevoid-canonical-host.env}"

TOTAL_STAGES=8

# remote "명령" — 서버에서 한 줄 실행하고 출력을 그대로 보여준다.
remote() { ssh "$SERVER" "$1"; }

banner "massivevoid.com — 정본 호스트 고정 (www → apex)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "안전장치 — 스냅샷과 SSH 확인"
say "이 절차는 Apache 설정과 TLS 인증서를 바꾼다. 실패하면 사이트가 내려갈 수 있다."
say "먼저 되돌릴 수 있는 상태를 만든다."
open_url "https://lightsail.aws.amazon.com/ls/webapp/home/instances"
step "인스턴스를 열고 Snapshots 탭 → 'Create snapshot' 을 눌러 스냅샷을 하나 만든다."
step "스냅샷 상태가 'Available' 이 될 때까지 기다린다(보통 몇 분)."
pause "스냅샷이 준비되면 Enter."
ask SERVER "SSH 접속 주소 [기본 ubuntu@3.35.99.208]:"
[[ -z "$SERVER" ]] && SERVER="ubuntu@3.35.99.208"
write_env SERVER "$SERVER"
say "접속을 확인한다."
remote "hostname && apache2ctl -v | head -1"
pause "접속과 Apache 버전이 보이면 Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "현재 상태 기록 + vhost 백업"
say "바꾸기 전의 응답과 설정 파일을 남겨둔다. 롤백의 기준점이다."
note "지금 상태 — 두 줄 모두 301이면 이미 적용된 상태이고, www가 200이면 고칠 것이 있다:"
printf '    '; curl -sI -o /dev/null -w 'http://massivevoid.com/      %{http_code} -> %{redirect_url}\n' http://massivevoid.com/
printf '    '; curl -sI -o /dev/null -w 'http://www.massivevoid.com/  %{http_code} -> %{redirect_url}\n' http://www.massivevoid.com/
say ""
say "서버의 vhost 파일을 타임스탬프 붙여 백업한다."
remote "sudo cp -v /etc/apache2/sites-available/kirby.conf /etc/apache2/sites-available/kirby.conf.bak.\$(date +%Y%m%d%H%M%S) && sudo cp -v /etc/apache2/sites-available/kirby-le-ssl.conf /etc/apache2/sites-available/kirby-le-ssl.conf.bak.\$(date +%Y%m%d%H%M%S)"
say ""
say "현재 vhost의 ServerName / ServerAlias / Rewrite 룰:"
remote "grep -nE 'ServerName|ServerAlias|RewriteCond|RewriteRule' /etc/apache2/sites-available/kirby.conf /etc/apache2/sites-available/kirby-le-ssl.conf || true"
warn "위 백업 파일 경로를 메모해둬라. 문제가 생기면 sudo cp <백업> <원본> && sudo systemctl reload apache2 로 되돌린다."
pause "백업이 만들어졌으면 Enter."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "vhost에 ServerAlias www 추가"
say "지금은 vhost가 ServerName massivevoid.com 하나뿐이라 www는 '우연히' 응답하고 있다."
say "www를 명시적으로 이 vhost의 것으로 만든다. certbot이 www 인증서를 발급하려면 이것이 먼저다."
if confirm "두 vhost(:80, :443)에 ServerAlias www.massivevoid.com 을 추가할까?"; then
  remote "for f in /etc/apache2/sites-available/kirby.conf /etc/apache2/sites-available/kirby-le-ssl.conf; do grep -q 'ServerAlias www.massivevoid.com' \$f || sudo sed -i '/ServerName massivevoid.com/a\\    ServerAlias www.massivevoid.com' \$f; done; grep -nE 'ServerName|ServerAlias' /etc/apache2/sites-available/kirby.conf /etc/apache2/sites-available/kirby-le-ssl.conf"
  say ""
  say "설정 문법을 검사한다. Syntax OK 가 아니면 여기서 멈춰라."
  remote "sudo apache2ctl configtest"
  if confirm "Syntax OK 였나? Apache를 reload 할까?"; then
    remote "sudo systemctl reload apache2 && echo reloaded"
  else
    warn "reload를 건너뛰었다. 백업으로 되돌리고 다시 시작하는 것을 권한다."
  fi
else
  warn "건너뛰었다 — 이후 certbot 단계가 www 인증서를 발급하지 못한다."
fi
pause "다음 단계로."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "인증서 재발급 — www 포함"
say "현재 인증서는 massivevoid.com 만 담고 있어서 https://www 는 TLS 연결 자체가 실패한다."
say "그런데 구글은 https://www.massivevoid.com/ 을 이미 크롤했다. 유효한 인증서를 주고 301로 넘겨야 한다."
warn "certbot은 vhost를 다시 쓰고 Apache를 재시작한다. 여기가 가장 되돌리기 어려운 지점이다."
note "실행할 명령:"
note "  sudo certbot --apache --cert-name massivevoid.com \\"
note "       -d massivevoid.com -d www.massivevoid.com --expand"
step "대화형 질문이 나오면: HTTP를 HTTPS로 리다이렉트할지 물을 때 '2: Redirect' 를 고른다."
if confirm "인증서를 재발급할까?"; then
  ssh -t "$SERVER" "sudo certbot --apache --cert-name massivevoid.com -d massivevoid.com -d www.massivevoid.com --expand"
  say ""
  say "인증서에 두 도메인이 들어갔는지 확인한다."
  remote "sudo certbot certificates | grep -A2 'massivevoid.com'"
else
  warn "건너뛰었다 — https://www 는 계속 TLS 오류를 낸다."
fi
pause "Domains 줄에 massivevoid.com 과 www.massivevoid.com 이 함께 보이면 Enter."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "www → apex 301 룰 추가"
say "이제 www는 유효한 인증서로 응답한다. 마지막으로 모든 www 요청을 apex로 넘긴다."
note "두 vhost의 <VirtualHost> 안에 넣을 룰:"
note "    RewriteEngine on"
note "    RewriteCond %{HTTP_HOST} ^www\\. [NC]"
note "    RewriteRule ^ https://massivevoid.com%{REQUEST_URI} [L,R=301]"
note "certbot이 만든 http→https 룰보다 앞에 두면 http://www 가 한 번에 apex로 간다."
if confirm "이 룰을 두 vhost에 넣을까?"; then
  remote "for f in /etc/apache2/sites-available/kirby.conf /etc/apache2/sites-available/kirby-le-ssl.conf; do grep -q 'HTTP_HOST} \\^www' \$f || sudo sed -i '/ServerAlias www.massivevoid.com/a\\    RewriteEngine on\\n    RewriteCond %{HTTP_HOST} ^www\\\\. [NC]\\n    RewriteRule ^ https://massivevoid.com%{REQUEST_URI} [L,R=301]' \$f; done; grep -nE 'HTTP_HOST|RewriteRule' /etc/apache2/sites-available/kirby.conf /etc/apache2/sites-available/kirby-le-ssl.conf"
  say ""
  remote "sudo apache2ctl configtest"
  if confirm "Syntax OK 였나? reload 할까?"; then
    remote "sudo systemctl reload apache2 && echo reloaded"
  else
    warn "백업으로 되돌려라: sudo cp <백업> <원본> && sudo systemctl reload apache2"
  fi
else
  warn "건너뛰었다 — www 복제본이 그대로 남는다. 이 작업의 핵심 단계다."
fi
pause "다음 단계로."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "앱 설정 배포 (2차 방어선)"
say "저장소에는 이미 정본 URL 고정이 들어가 있다:"
note "  site/config/config.massivevoid.com.php  → url = https://massivevoid.com"
note "  site/config/config.www.massivevoid.com.php (신규) → apex 설정을 그대로 물려받음"
note "  docs/adr/0003-canonical-host.md"
say "서버 설정이 언젠가 되돌아가더라도 canonical과 sitemap이 www로 새지 않게 하는 장치다."
step "먼저 로컬에서 커밋한다 (아직 안 했다면):"
note "  git add site/config docs/adr && git commit -m 'fix: 정본 호스트를 apex로 고정'"
step "그 다음 push 한 번으로 GitHub 백업 + 서버 배포가 동시에 된다:"
note "  git push origin main"
pause "커밋과 push가 끝났으면 Enter."
say "서버에 반영됐는지 확인한다."
remote "ls -la /var/www/html/kirby/site/config/"
pause "config.www.massivevoid.com.php 가 보이면 Enter."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "검증"
say "밖에서 실제로 어떻게 응답하는지 확인한다. 기대값을 함께 적었다."
printf '\n'
printf '  %-42s ' "http://massivevoid.com/"      ; curl -sI -o /dev/null -w '%{http_code} -> %{redirect_url}\n' http://massivevoid.com/
note "    기대: 301 -> https://massivevoid.com/"
printf '  %-42s ' "http://www.massivevoid.com/"  ; curl -sI -o /dev/null -w '%{http_code} -> %{redirect_url}\n' http://www.massivevoid.com/
note "    기대: 301 -> https://massivevoid.com/   (전에는 200이었다)"
printf '  %-42s ' "https://www.massivevoid.com/" ; curl -sI -o /dev/null -w '%{http_code} -> %{redirect_url}\n' https://www.massivevoid.com/
note "    기대: 301 -> https://massivevoid.com/   (전에는 TLS 실패)"
printf '  %-42s ' "https://massivevoid.com/"     ; curl -sI -o /dev/null -w '%{http_code}\n' https://massivevoid.com/
note "    기대: 200"
printf '\n'
say "canonical과 sitemap이 apex로만 나오는지:"
printf '    '; curl -s https://massivevoid.com/blog/2026-first | grep -o '<link rel="canonical"[^>]*>' || true
printf '    '; curl -s https://massivevoid.com/sitemap.xml | grep -o '<loc>[^<]*</loc>' | head -1 || true
note "    두 줄 모두 www 가 없어야 한다."
printf '\n'
say "www 쪽에서 Panel이 더는 노출되지 않는지:"
printf '    panel via www: '; curl -sI -o /dev/null -w '%{http_code} -> %{redirect_url}\n' http://www.massivevoid.com/panel
note "    기대: 301 (전에는 500 — 설정이 로드되지 않아 Panel이 살아 있었다)"
printf '\n'
warn "하나라도 기대와 다르면 GSC 단계로 넘어가지 말고 백업으로 되돌린 뒤 다시 보자."
pause "전부 기대대로면 Enter."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Search Console — 검증 시작"
say "고쳤다는 사실을 구글에 알려 재크롤 우선순위를 올린다."
open_url "https://search.google.com/search-console/index?resource_id=sc-domain%3Amassivevoid.com"
step "'Duplicate, Google chose different canonical than user' 행을 연다 → VALIDATE FIX."
step "뒤로 가서 'Crawled - currently not indexed' 행을 연다 → VALIDATE FIX."
note "나머지 세 행은 건드리지 않는다:"
note "  · Alternate page with proper canonical tag (?ref=…) — 정상 동작"
note "  · Page with redirect (http://massivevoid.com/) — 정상 동작"
note "  · Not found (404) (index.html) — 방치하기로 결정"
pause "두 행의 검증을 시작했으면 Enter."
open_url "https://search.google.com/search-console/sitemaps?resource_id=sc-domain%3Amassivevoid.com"
step "sitemap.xml 을 다시 제출한다 (URL 칸에 sitemap.xml 입력 → SUBMIT)."
note "미색인 8건은 마지막 크롤이 2~3월이라 반영까지 몇 주 걸릴 수 있다."
pause "제출했으면 Enter."

finish
