title: Site

sections:
  unlisted:
    type: pages
    status: unlisted

  listed:
    type: pages
    status: listed

  redirects:
    extends: plugin-redirects

tabs:
  content:
    fields:
      # your fields
  seo: seo/site
